[package]
name = "makefile"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
editfile = { path = "../editfile/" }

[build-dependencies]
cc = "1.0.67"
